Build:
  before_script:
    - apt-get update -qq
    - apt-get install -y make git autoconf automake libtool gettext autopoint cvs
    - apt-get install -y texinfo texlive texlive-generic-recommended texlive-extra-utils
    - apt-get install -y help2man gtk-doc-tools dblatex valgrind gengetopt
    - apt-get install -y transfig mono-mcs gperf default-jdk-headless
    - make bootstrap
  script:
    - make && make check
  artifacts:
    expire_in: 2 weeks
    when: on_failure
    paths:
      - ./*.log
      - tests/*.log
